# Remember that you can run git commands with the `--no-verify` flag to
# not run any hooks.

default_language_version:
    python: python{{cookiecutter.python_version}}

repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      # Tells pre-commit how to install the hook.
      language: python
      # File types to run on.
      types: [python]
